---
language: python
python:
  - "2.7"

# Install python packages for ansible and linters.
install:
  - "pip install -r requirements.txt"

# Execute linting and unit tests before running the main playbook.
before_script:
  - "echo 'brkrst3310' >> ~/vault_pass_file.txt"
  - "make lint unit"

# Perform playbook testing with mock CI inputs.
script:
  - "make pb"
