---
vrfs:
  - name: 1
    description: "first VRF"
    rd: "65000:1"
    route_import:
      - "65000:1"
    route_export:
      - "65000:2"
    interfaces:
      - "Loopback1"
    wipe_route_import: false
    wipe_route_export: false
    check:
      present: "10.3.3.0/30"
      absent: "10.2.2.0/30"

  - name: 2
    description: "second VRF"
    rd: "65000:2"
    route_import:
      - "65000:1"
    route_export:
      - "65000:2"
    interfaces:
      - "Loopback2"
    wipe_route_import: false
    wipe_route_export: false
    check:
      present: "10.3.3.0/30"
      absent: "10.1.1.0/30"

  - name: 3
    description: "third VRF"
    rd: "65000:3"
    route_import:
      - "65000:2"
    route_export:
      - "65000:1"
    interfaces:
      - "Loopback3"
    wipe_route_import: false
    wipe_route_export: false
    check:
      present: "10.1.1.0/30"
      absent: "100.64.0.0/10"
