---
vrfs:
  - name: "VRF1"
    description: "first VRF"
    rd: "65000:1"
    route_import:
      - "65000:1"  # optional comment here
    route_export:
      - "65000:2"  # optional comment here
    check:
      routes:
        - "10.3.3.0/30"
        - "10.4.4.0/24"
      pings:
        - "10.3.3.1"
        - "10.4.4.44"

  - name: "VRF2"
    description: "second VRF"
    rd: "65000:2"
    route_import:
      - "65000:1"  # optional comment here
    route_export:
      - "65000:2"  # optional comment here
    check: false

  - name: "VRF3"
    description: "third VRF"
    rd: "65000:3"
    route_import:
      - "65000:2"  # optional comment here
    route_export:
      - "65000:1"  # optional comment here
    check:
      routes:
        - "10.1.1.0/30"
        - "10.2.2.0/30"
      pings:
        - "10.1.1.1"
        - "10.2.2.1"
...
